const CLEAR_CONTACT_FORM = 'CLEAR_CONTACT_FORM';
const GET_ARTICLES = 'GET_ARTICLES';
const NAVIGATE_ARTICLE = 'NAVIGATE_ARTICLE';
const TOGGLE_ARTICLE = 'TOGGLE_ARTICLE';
const TOGGLE_AUTHORIZED = 'TOGGLE_AUTHORIZED';
const TOGGLE_MENU = 'TOGGLE_MENU';
const TOGGLE_MESSAGE_LOADER = 'TOGGLE_MESSAGE_LOADER';
const TOGGLE_MESSAGE_SUCCESS_BLOCK = 'TOGGLE_MESSAGE_SUCCESS_BLOCK';
const TOGGLE_PROJECT = 'TOGGLE_PROJECT';
const UPDATE_CONTACT_FORM = 'UPDATE_CONTACT_FORM';
const UPDATE_ERROR = 'UPDATE_ERROR';

export {
  CLEAR_CONTACT_FORM,
  GET_ARTICLES,
  NAVIGATE_ARTICLE,
  TOGGLE_ARTICLE,
  TOGGLE_AUTHORIZED,
  TOGGLE_MENU,
  TOGGLE_MESSAGE_LOADER,
  TOGGLE_MESSAGE_SUCCESS_BLOCK,
  TOGGLE_PROJECT,
  UPDATE_CONTACT_FORM,
  UPDATE_ERROR,
};
