const TOGGLE_MENU = 'TOGGLE_MENU';
const TOGGLE_PROJECT = 'TOGGLE_PROJECT';
const TOGGLE_ARTICLE = 'TOGGLE_ARTICLE';
const NAVIGATE_ARTICLE = 'NAVIGATE_ARTICLE';
const GET_ARTICLES = 'GET_ARTICLES';

export {
  TOGGLE_MENU,
  TOGGLE_PROJECT,
  TOGGLE_ARTICLE,
  NAVIGATE_ARTICLE,
  GET_ARTICLES,
};
