const ARTICLE_LIST_LOADING = 'ARTICLE_LIST_LOADING';
const CLEAR_CONTACT_FORM = 'CLEAR_CONTACT_FORM';
const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST';
const GET_PROJECT_LIST = 'GET_PROJECT_LIST';
const NAVIGATE_ARTICLE = 'NAVIGATE_ARTICLE';
const PROJECT_LIST_LOADING = 'PROJECT_LIST_LOADING';
const TOGGLE_ARTICLE = 'TOGGLE_ARTICLE';
const TOGGLE_AUTHORIZED = 'TOGGLE_AUTHORIZED';
const TOGGLE_MENU = 'TOGGLE_MENU';
const TOGGLE_MESSAGE_LOADER = 'TOGGLE_MESSAGE_LOADER';
const TOGGLE_MESSAGE_SUCCESS_BLOCK = 'TOGGLE_MESSAGE_SUCCESS_BLOCK';
const TOGGLE_PROJECT = 'TOGGLE_PROJECT';
const UPDATE_CONTACT_FORM = 'UPDATE_CONTACT_FORM';
const UPDATE_MESSAGE_ERROR = 'UPDATE_MESSAGE_ERROR';

export {
  ARTICLE_LIST_LOADING,
  CLEAR_CONTACT_FORM,
  GET_ARTICLE_LIST,
  GET_PROJECT_LIST,
  NAVIGATE_ARTICLE,
  PROJECT_LIST_LOADING,
  TOGGLE_ARTICLE,
  TOGGLE_AUTHORIZED,
  TOGGLE_MENU,
  TOGGLE_MESSAGE_LOADER,
  TOGGLE_MESSAGE_SUCCESS_BLOCK,
  TOGGLE_PROJECT,
  UPDATE_CONTACT_FORM,
  UPDATE_MESSAGE_ERROR,
};
