name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
      name: Deploying to surge
      runs-on: ubuntu-latest

      steps:
        #This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
        - name: Check out Git repository
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2-beta
          with:
            node-version: 12

        - name: Prepare for Yarn Installation
          run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

        - name: install yarn
          run: sudo apt update && sudo apt install yarn

        - name: Install Packages
          run: yarn install

        - name: Build React App
          run: yarn build

        # Deploying on Surge
        - name: Install Surge
          run: npm install -g surge

        - name: Run surge
          run: surge ./build alexprisazhny.ru --token ${{ secrets.SURGE_TOKEN }}
